apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mydeployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "40%"
      maxSurge: "50%"
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: nginx:1.8.0
