apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bind
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        service: bind
        commit: e311f982eb769835ca75d942bd2fd0d9890776fb
    spec:
      nodeSelector:
          nodetype: "hss"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: "service"
                  operator: "In"
                  values: ["bind"]
              topologyKey: "kubernetes.io/hostname"
              namespaces: []
      containers:
      - env:
        - name: SERVICE_53_IGNORE
          value: '"true"'
        - name: TZ
          value: US/Pacific
        image: bind
        name: named
        resources:
          limits:
            memory: "150Mi"
          requests:
            memory: "40Mi"
      restartPolicy: Always
