apiVersion: v1
items:
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:45:00Z
    name: kubernetes
    namespace: default
    resourceVersion: "6"
    selfLink: /api/v1beta1/endpoints/kubernetes?namespace=default
    uid: 14f60e33-e9d8-11e4-b436-0800278433f5
  subsets:
  - addresses:
    - IP: 10.245.1.2
    ports:
    - port: 6443
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:45:00Z
    name: kubernetes-ro
    namespace: default
    resourceVersion: "7"
    selfLink: /api/v1beta1/endpoints/kubernetes-ro?namespace=default
    uid: 14f62c39-e9d8-11e4-b436-0800278433f5
  subsets:
  - addresses:
    - IP: 10.245.1.2
    ports:
    - port: 7080
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:48:01Z
    name: pulp-db
    namespace: default
    resourceVersion: "97"
    selfLink: /api/v1beta1/endpoints/pulp-db?namespace=default
    uid: 8128f36c-e9d8-11e4-b436-0800278433f5
  subsets:
  - addresses:
    - IP: 10.246.1.3
      targetRef:
        kind: Pod
        name: pulp-db
        namespace: default
        resourceVersion: "96"
        uid: 82459855-e9d8-11e4-b436-0800278433f5
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:48:02Z
    name: pulp-http
    namespace: default
    resourceVersion: "59"
    selfLink: /api/v1beta1/endpoints/pulp-http?namespace=default
    uid: 81cc0ac9-e9d8-11e4-b436-0800278433f5
  subsets: []
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:48:03Z
    name: pulp-https
    namespace: default
    resourceVersion: "61"
    selfLink: /api/v1beta1/endpoints/pulp-https?namespace=default
    uid: 821cbdec-e9d8-11e4-b436-0800278433f5
  subsets: []
- apiVersion: v1
  kind: Endpoints
  metadata:
    creationTimestamp: 2015-04-23T16:48:02Z
    name: pulp-msg
    namespace: default
    resourceVersion: "89"
    selfLink: /api/v1beta1/endpoints/pulp-msg?namespace=default
    uid: 8178d2b7-e9d8-11e4-b436-0800278433f5
  subsets:
  - addresses:
    - IP: 10.246.1.2
      targetRef:
        kind: Pod
        name: pulp-msg
        namespace: default
        resourceVersion: "88"
        uid: 82705015-e9d8-11e4-b436-0800278433f5
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
kind: List
metadata: {}
