apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mydeployment
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: mydeployment
    subresource: scale
  minReplicas: 3
  maxReplicas: 12
