{
    "kind": "Service",
    "apiVersion": "v1",
    "metadata": {
        "name": "my-service2"
    },
    "spec": {
        "selector": {
            "app": "nginx"
        },
        "ports": [
            {
                "protocol": "TCP",
                "port": 80,
                "targetPort": 1992
            }
        ]
    }
}
